services:
  nimiq-node:
    image: ghcr.io/nimiq/core-rs-albatross:latest
    container_name: nimiq-node
    user: root
    ports:
      - '8648:8648'
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /home/nimiq/.nimiq
        cat > /home/nimiq/.nimiq/client.toml <<EOF
        [consensus]
        network = "dev-albatross"

        [rpc-server]
        bind = "0.0.0.0"
        port = 8648
        EOF
        exec /usr/local/bin/nimiq-client
