# .github/workflows/test-integration.yml
name: Integration Tests

on:
  push:
    branches: [main, test/**]
  pull_request:
    branches: [main]

jobs:
  test-with-local-node:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout RPC client
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Nimiq config for devnet
        run: |
          mkdir -p nimiq-data
          cat > nimiq-data/client.toml << 'EOF'
          [consensus]
          network = "dev-albatross"

          [rpc-server]
          bind = "0.0.0.0:8648"
          EOF
          echo "Created client.toml with dev-albatross network"

      - name: Pull Nimiq Docker image
        run: docker pull ghcr.io/nimiq/core-rs-albatross:latest

      - name: Start Nimiq node in Docker
        run: |
          docker run -d \
            --name nimiq-node \
            -v $(pwd)/nimiq-data:/home/nimiq/.nimiq \
            -p 8648:8648 \
            ghcr.io/nimiq/core-rs-albatross:latest

          echo "Started Nimiq node in Docker"
          sleep 5

      - name: Wait for node to be ready
        run: |
          echo "Waiting for node to be ready..."
          timeout=60
          elapsed=0

          while [ $elapsed -lt $timeout ]; do
            if curl -s -X POST http://127.0.0.1:8648 \
              -H "Content-Type: application/json" \
              -d '{"jsonrpc":"2.0","method":"getBlockNumber","params":[],"id":1}' \
              | grep -q "result"; then
              echo "✅ Node is ready!"
              exit 0
            fi

            echo "Waiting... ($elapsed seconds)"
            sleep 1
            elapsed=$((elapsed + 1))
          done

          echo "❌ Node did not become ready in time"
          echo "=== Docker logs ==="
          docker logs nimiq-node
          exit 1

      - name: Run smoke test
        run: pnpm test test/smoke.test.ts
        env:
          TEST_RPC_URL: http://127.0.0.1:8648
          TEST_WS_URL: ws://127.0.0.1:8648/ws

      - name: Show node logs on failure
        if: failure()
        run: |
          echo "=== Nimiq Node Logs ==="
          docker logs nimiq-node || echo "No logs found"

      - name: Stop Nimiq node
        if: always()
        run: |
          docker stop nimiq-node || true
          docker rm nimiq-node || true
          echo "Stopped Nimiq node"
